### PR TITLE
allows to use env var to specify ros args

### PR DESCRIPTION
**Pull request by koonpeng**
## What's new

This adds a way to specify the ros args using environment variables, this is needed to run rclnodejs with SROS. It requires v0.1.3 (not released yet) of [romi-js-rclnodejs-transport](https://github.com/osrf/romi-js-rclnodejs-transport).

## Self-checks

- [x] I'm familiar with and follow this [ Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [x] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion

[Questions for reviewers]

### CODE REVIEW

**Comment by matiasbavera** [comment]
On hold until `romi-js-rclnodejs-transport`  v0.1.3 is released?

Now the `RclnodejsTransport.create(config.ros2NodeName);`
supports only one parameter
`static create(nodeName: string): Promise<RclnodejsTransport>;`

**Comment by koonpeng** [comment]
Yep, I was testing out some stuff before releasing v0.1.3

**Comment by koonpeng** [comment]
Turns out we don't really need this as SROS2 already allows us to specify the args in a env var. But I went ahead and publish v0.1.3 anyway since it's the feature is already done.

**Review by matiasbavera — APPROVED** [review]
LGTM

**Pull request merged**
