### PR TITLE
remove unused component

### PR DESCRIPTION
**Pull request by ChawinTan**
## What's new

fixes # [related issue, if exist]

Unused Dashboard tour components and tour props is causing build to fail.

[Describe your changes]

Remove the unused components

## Self-checks

- [x] I'm familiar with and follow this [ Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [x] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion

[Questions for reviewers]

### CODE REVIEW

**Comment by koonpeng** [comment]
Since the e2e CI is not working, have you tried a test run locally?

**Comment by ChawinTan** [comment]
A stand alone build compiles fine but with warnings. Running npm run test:e2e however causes the build to fail both locally and remotely.

**Comment by ChawinTan** [comment]
If this change is unnecessary or the code is left there on purpose then I will just comment out the code on my own e2e pr

**Comment by koonpeng** [comment]
@vallq can you review this, if these code are safe to remove?

**Comment by vallq** [comment]
just saw this, and yes, removing those components should not affect anything else because we are not rendering them anywhere for now

**Review by matiasbavera — APPROVED** [review]
LGTM, I'll write a description on the squash and merge

**Pull request merged**
